Projet_Synfoni/src/Entity/Choix.php
<?php

namespace App\Entity;

use App\Repository\ChoixRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ChoixRepository::class)]
class Choix
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;


    #[ORM\Column(length: 255)]
    private ?string $NomChoix = null;

    #[ORM\Column(length: 255)]
    private ?string $TextChoix = null;

    #[ORM\Column(type: Types::ARRAY)]
    private array $ConsequenceChoix = [];

    #[ORM\ManyToOne(inversedBy: 'LesChoix')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Niveau $LeNiveau = null;

    public function __construct() {}

    public function getId(): ?int
    {
        return $this->id;
    }



    public function getNomChoix(): ?string
    {
        return $this->NomChoix;
    }

    public function setNomChoix(string $NomChoix): static
    {
        $this->NomChoix = $NomChoix;

        return $this;
    }

    public function getTextChoix(): ?string
    {
        return $this->TextChoix;
    }

    public function setTextChoix(string $TextChoix): static
    {
        $this->TextChoix = $TextChoix;

        return $this;
    }

    public function getConsequenceChoix(): array
    {
        return $this->ConsequenceChoix;
    }

    public function setConsequenceChoix(array $ConsequenceChoix): static
    {
        $this->ConsequenceChoix = $ConsequenceChoix;

        return $this;
    }

    public function getLeNiveau(): ?Niveau
    {
        return $this->LeNiveau;
    }

    public function setLeNiveau(?Niveau $LeNiveau): static
    {
        $this->LeNiveau = $LeNiveau;

        return $this;
    }

    public function __toString(): string
    {
        return $this->LeNiveau;
    }
}

Projet_Synfoni/src/Entity/Niveau.php
<?php

namespace App\Entity;

use App\Repository\NiveauRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: NiveauRepository::class)]
class Niveau
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    /**
     * @var Collection<int, Scenario>
     */
    #[ORM\OneToMany(targetEntity: Scenario::class, mappedBy: 'niveau')]
    private Collection $IdScenario;

    #[ORM\Column(length: 255)]
    private ?string $NomNiveau = null;

    #[ORM\Column(length: 255)]
    private ?string $TextNiveau = null;

    /**
     * @var Collection<int, Choix>
     */
    #[ORM\OneToMany(targetEntity: Choix::class, mappedBy: 'LeNiveau')]
    private Collection $LesChoix;

    #[ORM\ManyToOne(inversedBy: 'LesNiveaux')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Scenario $LeScenario = null;


    public function __construct()
    {
        $this->IdScenario = new ArrayCollection();
        $this->LesChoix = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return Collection<int, Scenario>
     */
    public function getIdScenario(): Collection
    {
        return $this->IdScenario;
    }

    public function addIdScenario(Scenario $idScenario): static
    {
        if (!$this->IdScenario->contains($idScenario)) {
            $this->IdScenario->add($idScenario);
            $idScenario->setNiveau($this);
        }

        return $this;
    }

    public function removeIdScenario(Scenario $idScenario): static
    {
        if ($this->IdScenario->removeElement($idScenario)) {
            // set the owning side to null (unless already changed)
            if ($idScenario->getNiveau() === $this) {
                $idScenario->setNiveau(null);
            }
        }

        return $this;
    }

    public function getNomNiveau(): ?string
    {
        return $this->NomNiveau;
    }

    public function setNomNiveau(string $NomNiveau): static
    {
        $this->NomNiveau = $NomNiveau;

        return $this;
    }

    public function getTextNiveau(): ?string
    {
        return $this->TextNiveau;
    }

    public function setTextNiveau(string $TextNiveau): static
    {
        $this->TextNiveau = $TextNiveau;

        return $this;
    }

    /**
     * @return Collection<int, Choix>
     */
    public function getLesChoix(): Collection
    {
        return $this->LesChoix;
    }

    public function addLesChoix(Choix $lesChoix): static
    {
        if (!$this->LesChoix->contains($lesChoix)) {
            $this->LesChoix->add($lesChoix);
            $lesChoix->setLeNiveau($this);
        }

        return $this;
    }

    public function removeLesChoix(Choix $lesChoix): static
    {
        if ($this->LesChoix->removeElement($lesChoix)) {
            // set the owning side to null (unless already changed)
            if ($lesChoix->getLeNiveau() === $this) {
                $lesChoix->setLeNiveau(null);
            }
        }

        return $this;
    }

    public function getLeScenario(): ?Scenario
    {
        return $this->LeScenario;
    }

    public function setLeScenario(?Scenario $LeScenario): static
    {
        $this->LeScenario = $LeScenario;

        return $this;
    }

    public function __toString(): string
    {
        return $this->NomNiveau;
    }
}

Projet_Synfoni/src/Entity/Scenario.php
<?php

namespace App\Entity;

use App\Repository\ScenarioRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ScenarioRepository::class)]
class Scenario
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $NomScenario = null;


    /**
     * @var Collection<int, Niveau>
     */
    #[ORM\OneToMany(targetEntity: Niveau::class, mappedBy: 'LeScenario', orphanRemoval: true)]
    private Collection $LesNiveaux;

    #[ORM\Column(length: 1024)]
    private ?string $Description = null;

    public function __construct()
    {
        $this->LesNiveaux = new ArrayCollection();
    }

    // #[ORM\ManyToOne(inversedBy: 'IdScenario')]
    // private ?Niveau $niveau = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomScenario(): ?string
    {
        return $this->NomScenario;
    }

    public function setNomScenario(string $NomScenario): static
    {
        $this->NomScenario = $NomScenario;

        return $this;
    }



    // public function getNiveau(): ?Niveau
    // {
    //     return $this->niveau;
    // }

    // public function setNiveau(?Niveau $niveau): static
    // {
    //     $this->niveau = $niveau;

    //     return $this;
    // }

    /**
     * @return Collection<int, Niveau>
     */
    public function getLesNiveaux(): Collection
    {
        return $this->LesNiveaux;
    }

    public function addLesNiveau(Niveau $lesNiveau): static
    {
        if (!$this->LesNiveaux->contains($lesNiveau)) {
            $this->LesNiveaux->add($lesNiveau);
            $lesNiveau->setLeScenario($this);
        }

        return $this;
    }

    public function removeLesNiveau(Niveau $lesNiveau): static
    {
        if ($this->LesNiveaux->removeElement($lesNiveau)) {
            // set the owning side to null (unless already changed)
            if ($lesNiveau->getLeScenario() === $this) {
                $lesNiveau->setLeScenario(null);
            }
        }

        return $this;
    }

    public function __toString(): string
    {
        return $this->NomScenario;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): static
    {
        $this->Description = $Description;

        return $this;
    }
}

Projet_Synfoni/src/Controller/StoryController.php
<?php

namespace App\Controller;

use App\Entity\Choix;
use App\Entity\Niveau;
use App\Entity\Scenario;
use App\Entity\Personnage;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

final class StoryController extends AbstractController
{
    private EntityManagerInterface $entityManager;

    public function __construct(EntityManagerInterface $entityManager)
    {
        $this->entityManager = $entityManager;
    }

    #[Route('/story', name: 'story')]
    public function index(): Response
    {
        $scenarios = $this->entityManager->getRepository(Scenario::class)->findAll();

        // Générer les slugs pour chaque scénario
        $scenariosWithSlugs = array_map(function ($scenario) {
            return [
                'scenario' => $scenario,
                'slug' => $this->slugify($scenario->getNomScenario())
            ];
        }, $scenarios);

        return $this->render('story/index.html.twig', [
            'scenarios' => $scenariosWithSlugs,
        ]);
    }

    #[Route('/story/{slug}/{niveauId?}', name: 'story_show')]
    public function show(string $slug, ?int $niveauId = null): Response
    {
        $scenario = $this->entityManager->getRepository(Scenario::class)->findOneBy(['NomScenario' => str_replace('-', ' ', $slug)]);
    
        if (!$scenario) {
            throw $this->createNotFoundException('Le scénario n\'existe pas');
        }
    
        if ($niveauId === null) {
            $niveau = $scenario->getLesNiveaux()->first();
        } else {
            $niveau = $this->entityManager->getRepository(Niveau::class)->find($niveauId);
        }
    
        if (!$niveau) {
            throw $this->createNotFoundException('Aucun niveau trouvé pour ce scénario');
        }
    
        $choix = $niveau->getLesChoix();
        $personnage = $this->entityManager->getRepository(Personnage::class)->findOneBy([], ['id' => 'DESC']);

    
        // Vérifiez si les caractéristiques existent pour le personnage
        $caracteristiques = $personnage ? $personnage->getAura() : null;
    
        return $this->render('story/show.html.twig', [
            'scenario' => $scenario,
            'niveau' => $niveau,
            'choix' => $choix,
            'personnage' => $personnage,
            'caracteristiques' => $caracteristiques,
        ]);
    }
        
    #[Route('/story/{slug}/{niveauId}/{choixId}', name: 'story_choix')]
    public function choix(string $slug, int $niveauId, int $choixId): Response
    {
        $scenario = $this->entityManager->getRepository(Scenario::class)->findOneBy(['NomScenario' => str_replace('-', ' ', $slug)]);
        $niveau = $this->entityManager->getRepository(Niveau::class)->find($niveauId);
        $choix = $this->entityManager->getRepository(Choix::class)->find($choixId);
        $personnage = $this->entityManager->getRepository(Personnage::class)->findOneBy([], ['id' => 'DESC']);

        if (!$scenario || !$niveau || !$choix) {
            throw $this->createNotFoundException('Le scénario, le niveau ou le choix n\'existe pas');
        }

        // Appliquer les conséquences du choix
        if ($personnage && $personnage->getAura()) {
            $caracteristiques = $personnage->getAura();
            $consequences = $choix->getConsequenceChoix();

            // Appliquer chaque modification de manière ordonnée
            $caracteristiques->setAura($caracteristiques->getAura() + ($consequences[0] ?? 0));
            $caracteristiques->setHumour($caracteristiques->getHumour() + ($consequences[1] ?? 0));
            $caracteristiques->setCharisme($caracteristiques->getCharisme() + ($consequences[2] ?? 0));
            $caracteristiques->setPertinence($caracteristiques->getPertinence() + ($consequences[3] ?? 0));
            $caracteristiques->setIntelligence($caracteristiques->getIntelligence() + ($consequences[4] ?? 0));

            // Sauvegarder les modifications
            $this->entityManager->persist($caracteristiques);
            $this->entityManager->flush();

            // Ajouter un message flash pour afficher le texte du choix
            $this->addFlash('choiceText', $choix->getTextChoix());
        }

        // Si l'Aura est à 0 ou en dessous, rediriger vers une page de défaite
        if ($caracteristiques->getAura() <= 0) {
            return $this->render('story/loss.html.twig', [
                'scenario' => $scenario,
            ]);
        }

        // Déterminer le niveau suivant
        $nextNiveau = $this->entityManager->getRepository(Niveau::class)->find($niveauId + 1);

        if (!$nextNiveau) {
            return $this->render('story/end.html.twig', [
                'scenario' => $scenario,
            ]);
        }

        return $this->redirectToRoute('story_show', [
            'slug' => $slug,
            'niveauId' => $nextNiveau->getId(),
        ]);
    }

    private function slugify(string $text): string
    {
        // Remplace les espaces par des tirets
        $text = str_replace(' ', '-', $text);
        // Supprime les caractères non alphanumériques
        $text = preg_replace('/[^A-Za-z0-9\-]/', '', $text);
        // Convertit en minuscules
        return strtolower($text);
    }
}

Projet_Synfoni/templates/story/end.html.twig
{% extends 'base.html.twig' %}

{% block title %}Fin du scénario
{% endblock %}

{% block stylesheets %}
	<style>
		.end-game-container {
			background-color: #2d0035; /* Fond sombre pour la page */
			color: #f8f1f1; /* Texte clair */
			min-height: 100vh; /* Hauteur minimale de la page */
			display: flex;
			flex-direction: column;
			justify-content: center;
			align-items: center;
			text-align: center;
		}

		.end-game-container h1 {
			color: #ffe066; /* Couleur dorée pour le titre */
			font-size: 3rem;
			font-weight: bold;
		}

		.end-game-container p {
			font-size: 1.5rem;
			color: #f0d3f7; /* Couleur douce pour le texte */
		}

		.end-game-container a {
			font-size: 1.2rem;
			color: #ff69b4; /* Lien rose pour le retour */
			text-decoration: none;
			font-weight: bold;
		}

		.end-game-container a:hover {
			text-decoration: underline;
		}
	</style>
{% endblock %}

{% block body %}
	<div class="end-game-container">
		<h1>Félicitations !</h1>
		<p>Vous avez trempé le biscuit avec brio... et l'aventure ne fait que commencer. Préparez-vous pour des surprises encore plus épicées la prochaine fois !</p>
		<a href="{{ path('story') }}">Retour à la liste des rendez-vous</a>
	</div>
{% endblock %}

Projet_Synfoni/templates/story/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Choisissez un scénario
{% endblock %}

{% block personnage_stats %}
	{% if personnage is defined %}
		{% include 'components/personnage_stats.html.twig' %}
	{% endif %}
{% endblock %}

{% block body %}
	<div class="container py-5" style="background-color: #2d0035; color: #f8f1f1; min-height: 100vh;">
		<div class="row justify-content-center">
			<div class="col-md-8 text-center">

				<h1 class="mb-4" style="color: #f8f1f1; font-size: 2.5rem; font-weight: bold;">
					Date disponibles
				</h1>

				<p class="mb-4" style="font-size: 1.2rem; color: #f0d3f7;">
					Plongez dans des histoires captivantes. Sélectionnez un scénario et laissez votre personnage faire ses preuves.
				</p>

				{% for message in app.flashes('error') %}
					<div class="alert alert-danger alert-dismissible fade show" role="alert">
						{{ message }}
						<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
					</div>
				{% endfor %}

				{% for message in app.flashes('success') %}
					<div class="alert alert-success alert-dismissible fade show" role="alert">
						{{ message }}
						<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
					</div>
				{% endfor %}

				<div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 g-4">
					{% for item in scenarios %}
						<div class="col">
							<div class="card h-100 shadow" style="background-color: #4a0066; border: 2px solid #ff69b4; border-radius: 10px;">
								<div class="card-body text-center p-4">
									<h5 class="card-title mb-3" style="color: #ffe066; font-weight: bold;">
										{{ item.scenario.NomScenario }}
									</h5>
									<p class="card-text" style="color: #d9b3ff;">
										{{ item.scenario.description }}
									</p>
									<a href="{{ path('story_show', {slug: item.slug}) }}" class="btn" style="background-color: #ff69b4; color: #fff; font-weight: bold; border-radius: 5px; width: 100%;">
										Commencer
									</a>
								</div>
							</div>
						</div>
					{% endfor %}
				</div>

			</div>
		</div>
	</div>
{% endblock %}

Projet_Synfoni/templates/story/loss.html.twig
{% extends 'base.html.twig' %}

{% block title %}Fin du scénario - Perte
{% endblock %}

{% block stylesheets %}
	<style>
		.lose-game-container {
			background-color: #2d0035; /* Fond sombre pour la page */
			color: #f8f1f1; /* Texte clair */
			min-height: 100vh; /* Hauteur minimale de la page */
			display: flex;
			flex-direction: column;
			justify-content: center;
			align-items: center;
			text-align: center;
		}

		.lose-game-container h1 {
			color: #ff6347; /* Couleur rouge orangé pour indiquer la perte */
			font-size: 3rem;
			font-weight: bold;
		}

		.lose-game-container p {
			font-size: 1.5rem;
			color: #f0d3f7; /* Couleur douce pour le texte */
		}

		.lose-game-container a {
			font-size: 1.2rem;
			color: #ff69b4; /* Lien rose pour le retour */
			text-decoration: none;
			font-weight: bold;
		}

		.lose-game-container a:hover {
			text-decoration: underline;
		}
	</style>
{% endblock %}

{% block body %}
	<div class="lose-game-container">
		<h1>Game Over, t'as foiré puceau.</h1>
		<p>Retourne te toucher la nouille, t'as perdu toute crédibilité dans ce jeu.</p>
		<a href="{{ path('story') }}">Essaie encore si t'oses.</a>
	</div>
{% endblock %}

Projet_Synfoni/templates/story/show.html.twig
{% extends 'base.html.twig' %}

{% block body %}
	<div class="container py-3" style="background-color: #5E2B8A; color: #F5F5F5; border-radius: 15px;">
		<div class="row text-center">
			<h1 class="text-warning mb-3">{{ scenario.NomScenario }}</h1>
			<h2 class="text-light mb-4">Niveau:
				{{ niveau.nomNiveau }}</h2>
		</div>

		<!-- Affichage des messages flash -->
		<div class="row">
			<div class="col-12">
				{% for message in app.flashes('success') %}
					<div class="alert alert-success">{{ message }}</div>
				{% endfor %}
				{% for message in app.flashes('choiceText') %}
					<div class="alert alert-info">{{ message }}</div>
					<!-- Affichage du texte du choix -->
				{% endfor %}
			</div>
		</div>

		<div class="row mb-3">
			<div class="col-12">
				<h3 class="text-pink">Situation:</h3>
				<p>{{ niveau.TextNiveau }}</p>
			</div>
		</div>

		<div class="row justify-content-center mb-4">
			<div class="col-md-8 text-center">
				<h3 class="text-pink">Statistiques du personnage:</h3>
				{% if caracteristiques %}
					<ul class="list-unstyled">
						<li>
							<strong>Aura:</strong>
							{{ caracteristiques.Aura }}</li>
						<li>
							<strong>Humour:</strong>
							{{ caracteristiques.Humour }}</li>
						<li>
							<strong>Charisme:</strong>
							{{ caracteristiques.Charisme }}</li>
						<li>
							<strong>Pertinence:</strong>
							{{ caracteristiques.Pertinence }}</li>
						<li>
							<strong>Intelligence:</strong>
							{{ caracteristiques.Intelligence }}</li>
					</ul>
				{% else %}
					<p>Aucune caractéristique disponible pour ce personnage.</p>
				{% endif %}
			</div>
		</div>

		<div class="row mb-3">
			<div class="col-12 text-center">
				<h3 class="text-pink">Choix disponibles</h3>
				<div class="d-flex flex-wrap justify-content-center">
					{% for choix in choix %}
						<a href="{{ path('story_choix', { 'slug': scenario.NomScenario|replace({' ': '-'})|lower, 'niveauId': niveau.id, 'choixId': choix.id }) }}" class="btn m-2" style="background: linear-gradient(135deg, #FF69B4, #5E2B8A); color: #F5F5F5; border: none; border-radius: 10px; padding: 10px 20px;">
							{{ choix.nomChoix }}
						</a>
					{% endfor %}
				</div>
			</div>
		</div>
	</div>
{% endblock %}